/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReturnItemsRouteImport } from './routes/return-items'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RentalsRouteImport } from './routes/rentals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DueProductsRouteImport } from './routes/due-products'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AvailabilityRouteImport } from './routes/availability'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers/$customerId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnItemsRoute = ReturnItemsRouteImport.update({
  id: '/return-items',
  path: '/return-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RentalsRoute = RentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DueProductsRoute = DueProductsRouteImport.update({
  id: '/due-products',
  path: '/due-products',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AvailabilityRoute = AvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/approvals': typeof ApprovalsRoute
  '/availability': typeof AvailabilityRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRouteWithChildren
  '/deliveries': typeof DeliveriesRoute
  '/due-products': typeof DueProductsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/rentals': typeof RentalsRoute
  '/reports': typeof ReportsRoute
  '/return-items': typeof ReturnItemsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/approvals': typeof ApprovalsRoute
  '/availability': typeof AvailabilityRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRouteWithChildren
  '/deliveries': typeof DeliveriesRoute
  '/due-products': typeof DueProductsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/rentals': typeof RentalsRoute
  '/reports': typeof ReportsRoute
  '/return-items': typeof ReturnItemsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/approvals': typeof ApprovalsRoute
  '/availability': typeof AvailabilityRoute
  '/calendar': typeof CalendarRoute
  '/customers': typeof CustomersRouteWithChildren
  '/deliveries': typeof DeliveriesRoute
  '/due-products': typeof DueProductsRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/rentals': typeof RentalsRoute
  '/reports': typeof ReportsRoute
  '/return-items': typeof ReturnItemsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/approvals'
    | '/availability'
    | '/calendar'
    | '/customers'
    | '/deliveries'
    | '/due-products'
    | '/inventory'
    | '/login'
    | '/rentals'
    | '/reports'
    | '/return-items'
    | '/settings'
    | '/signup'
    | '/customers/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/approvals'
    | '/availability'
    | '/calendar'
    | '/customers'
    | '/deliveries'
    | '/due-products'
    | '/inventory'
    | '/login'
    | '/rentals'
    | '/reports'
    | '/return-items'
    | '/settings'
    | '/signup'
    | '/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/approvals'
    | '/availability'
    | '/calendar'
    | '/customers'
    | '/deliveries'
    | '/due-products'
    | '/inventory'
    | '/login'
    | '/rentals'
    | '/reports'
    | '/return-items'
    | '/settings'
    | '/signup'
    | '/customers/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AvailabilityRoute: typeof AvailabilityRoute
  CalendarRoute: typeof CalendarRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  DeliveriesRoute: typeof DeliveriesRoute
  DueProductsRoute: typeof DueProductsRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  RentalsRoute: typeof RentalsRoute
  ReportsRoute: typeof ReportsRoute
  ReturnItemsRoute: typeof ReturnItemsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-items': {
      id: '/return-items'
      path: '/return-items'
      fullPath: '/return-items'
      preLoaderRoute: typeof ReturnItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rentals': {
      id: '/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof RentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/due-products': {
      id: '/due-products'
      path: '/due-products'
      fullPath: '/due-products'
      preLoaderRoute: typeof DueProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/availability': {
      id: '/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof AvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
  }
}

interface CustomersRouteChildren {
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApprovalsRoute: ApprovalsRoute,
  AvailabilityRoute: AvailabilityRoute,
  CalendarRoute: CalendarRoute,
  CustomersRoute: CustomersRouteWithChildren,
  DeliveriesRoute: DeliveriesRoute,
  DueProductsRoute: DueProductsRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  RentalsRoute: RentalsRoute,
  ReportsRoute: ReportsRoute,
  ReturnItemsRoute: ReturnItemsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
